language: node_js
dist: trusty
sudo: required
node_js:
  - lts/*
notifications:
  email:
    recipients:
      - felix.hammerl@gmail.com
addons:
  chrome: stable
before_script:
  - mkdir -p /tmp/bin && wget -P /tmp/bin https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip && unzip /tmp/bin/chromedriver_linux64.zip
  - export PATH=/tmp/bin:$PATH
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xvfb to boot
  - sudo cp crt/rootCA.pem /usr/local/share/ca-certificates/
  - sudo cp crt/server.crt /usr/local/share/ca-certificates/
  - sudo update-ca-certificates

